### ISSUE TITLE
Compute t-0 covariate balance in v2.0.1

### ISSUE THREAD

**Issue by jjharden** [insongkim/PanelMatch#104]
In version 2.0.0 of the package, get_covariate_balance() would compute balance for the lag window and time t-0. It appears that in version 2.0.1 the function begins with time t-1. Is there a reason for this change? And is there a simple way to ask the function to compute balance at t-0?

**Comment by insongkim** [comment]
@jjharden We made the change because the balance is supposed to be computed for the ***pre***-treatment periods. Since PanelMatch considers t-0 as the treatment period, the balance is presented from t-1 up to t-l. I hope this makes sense. Thank you very much!
