### ISSUE TITLE
Change in the computation of bootstrapped SE?

### ISSUE THREAD

**Issue by augustocerqua** [insongkim/PanelMatch#109]
Dear Authors,

I have recently worked on a code I created last year using PanelMatch. After running the estimates, I noticed that the point estimates are the same as they used to be, while I noticed a steep increase in the standard errors (between +20 and +30%). As my code has not changed over the last year (Mahalanobis matching, with bootstrapped SE and 1,000 iterations), this might be due to the use of a novel version of R or, more likely, to some updates to PanelMatch/PanelEstimate. Is it possible you modified the way PanelEstimate computes bootstrapped standard errors over the last few months?

Many thanks,
Augusto Cerqua

**Comment by adamrauh** [comment]
Hi Augusto, 

Yes, we did make some updates to PanelEstimate a little while ago that would have exactly this kind of result. So, this seems like the most likely explanation. We did also add analytical standard errors in recent version of the package, which you may be interested in trying out as well.

Thanks for your continued use of the package. Let us know if you have other questions.
-Adam

**Comment by augustocerqua** [comment]
Dear Adam,

Many thanks for the reply. Yes, I noticed the addition of the analytical SE. Any specific guidance on when to use the analytical SE rather than the bootstrapped ones?

Thanks again for the support,
Augusto

**Comment by adamrauh** [comment]
The [paper](https://imai.fas.harvard.edu/research/files/tscs.pdf) goes over the various assumptions that each type makes (starting on page 11). So, there are no hard and fast rules, but the conditional standard errors will make a few extra assumptions, which may or may not be defensible in your particular application. 

Aside from that, the analytical standard errors will be faster to compute. But, there are a few cases where we haven't implemented them yet, so the option is not available.

**Comment by augustocerqua** [comment]
Many thanks Adam. Your reply is very clear.

Thanks for the support,
Augusto
