### ISSUE TITLE
Extract data from matched set object

### ISSUE THREAD

**Issue by ilango2486** [insongkim/PanelMatch#122]
Hi @adamrauh, is there a way to extract the matched control units for each treated unit from the matched set object? Currently, I can view the object as a list of control units and weights for each treated unit by calling something like matched.set$att[[1]]. However, I am not able to filter the control units for the treated unit. Is there a work around for getting the list?

**Comment by adamrauh** [comment]
Is [this](https://github.com/insongkim/PanelMatch/wiki/Matched-Set-Objects) helpful? If I understand correctly, you are quite close to having what you want. If you index into the matched.set object with the id + time of treatment of the treated unit, it should return to you a vector of control unit ids (and the weights, if you want them).

**Comment by ilango2486** [comment]
Thank you. This is very helpful!
