### ISSUE TITLE
Issue with refinement: non-numeric data exists and size.match

### ISSUE THREAD

**Issue by mathurshreya95** [insongkim/PanelMatch#126]
Hi,

I'm trying to use the panel match command as follows:

```
matches2 <- PanelMatch(lag = 1, time.id = "time_id",
            unit.id = "unit_id",
            treatment = "novel_current",
            refinement.method = "ps.match",
            data = as.data.frame(dt),
            match.missing = F,
            covs.formula = ~ atq + emp + piq + seqq,
            qoi = "att",
            size.match = 2,
            outcome.var = 'as_spot_spend',
            lead = 0)  
```

However, I get the warning message:
```
Warning message:
In panel_match(lag, time.id, unit.id, treatment, refinement.method,  :
  non-numeric data exists. Only numeric (including binary) data can be used for refinement and calculations
``` 

1. I checked the class of my treatment variable and covariates. They are all numeric and have no missing values. The data is not balanced in that every unit has a different year of entry but I do not understand why I am getting this warning message. 
2. Even after using size.match=2, I am getting much larger matched.sets. Could someone explain why?

Thanks!

**Comment by adamrauh** [comment]
1. That warning message appears if you have any non-numeric data in the data frame that you pass to PanelMatch(). If you aren't using those columns anywhere in the matching/refinement process, then you don't need to worry about the warning.
2. Changing size.match sets the number of control units that receive non-zero weight -- take a look at an individual matched set and you should be able to verify that. It doesn't change the number of controls matched to each treated observation based on the treatment history (which is the quantity that appears in the summary view).
