### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by carlokoos** [insongkim/PanelMatch#17]
> library(devtools)
> install_github("insongkim/PanelMatch", dependencies=TRUE)
Downloading GitHub repo insongkim/PanelMatch@master
Installing 21 packages: CBPS, DataCombine, evaluate, foreach, glmnet, highr, iterators, kernlab, knitr, lasso2, markdown, Matching, MatchIt, matrixStats, mcmc, MCMCpack, optimx, Rsolnp, Synth, truncnorm, yaml
Installing packages into ‘C:/Users/User/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/CBPS_0.19.zip'
Content type 'application/zip' length 154789 bytes (151 KB)
downloaded 151 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/DataCombine_0.2.21.zip'
Content type 'application/zip' length 87094 bytes (85 KB)
downloaded 85 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/evaluate_0.12.zip'
Content type 'application/zip' length 48684 bytes (47 KB)
downloaded 47 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/foreach_1.4.4.zip'
Content type 'application/zip' length 388505 bytes (379 KB)
downloaded 379 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/glmnet_2.0-16.zip'
Content type 'application/zip' length 1739382 bytes (1.7 MB)
downloaded 1.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/highr_0.7.zip'
Content type 'application/zip' length 36796 bytes (35 KB)
downloaded 35 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/iterators_1.0.10.zip'
Content type 'application/zip' length 320502 bytes (312 KB)
downloaded 312 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/kernlab_0.9-27.zip'
Content type 'application/zip' length 2246269 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/knitr_1.20.zip'
Content type 'application/zip' length 917447 bytes (895 KB)
downloaded 895 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/lasso2_1.2-20.zip'
Content type 'application/zip' length 245798 bytes (240 KB)
downloaded 240 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/markdown_0.8.zip'
Content type 'application/zip' length 168948 bytes (164 KB)
downloaded 164 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Matching_4.9-3.zip'
Content type 'application/zip' length 940793 bytes (918 KB)
downloaded 918 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/MatchIt_3.0.2.zip'
Content type 'application/zip' length 367152 bytes (358 KB)
downloaded 358 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/matrixStats_0.54.0.zip'
Content type 'application/zip' length 1634563 bytes (1.6 MB)
downloaded 1.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/mcmc_0.9-5.zip'
Content type 'application/zip' length 1430266 bytes (1.4 MB)
downloaded 1.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/MCMCpack_1.4-4.zip'
Content type 'application/zip' length 2855621 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/optimx_2018-7.10.zip'
Content type 'application/zip' length 894872 bytes (873 KB)
downloaded 873 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Rsolnp_1.16.zip'
Content type 'application/zip' length 172024 bytes (167 KB)
downloaded 167 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/Synth_1.1-5.zip'
Content type 'application/zip' length 105290 bytes (102 KB)
downloaded 102 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/truncnorm_1.0-8.zip'
Content type 'application/zip' length 42287 bytes (41 KB)
downloaded 41 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/yaml_2.2.0.zip'
Content type 'application/zip' length 200366 bytes (195 KB)
downloaded 195 KB

package ‘CBPS’ successfully unpacked and MD5 sums checked
package ‘DataCombine’ successfully unpacked and MD5 sums checked
package ‘evaluate’ successfully unpacked and MD5 sums checked
package ‘foreach’ successfully unpacked and MD5 sums checked
package ‘glmnet’ successfully unpacked and MD5 sums checked
package ‘highr’ successfully unpacked and MD5 sums checked
package ‘iterators’ successfully unpacked and MD5 sums checked
package ‘kernlab’ successfully unpacked and MD5 sums checked
package ‘knitr’ successfully unpacked and MD5 sums checked
package ‘lasso2’ successfully unpacked and MD5 sums checked
package ‘markdown’ successfully unpacked and MD5 sums checked
package ‘Matching’ successfully unpacked and MD5 sums checked
package ‘MatchIt’ successfully unpacked and MD5 sums checked
package ‘matrixStats’ successfully unpacked and MD5 sums checked
package ‘mcmc’ successfully unpacked and MD5 sums checked
package ‘MCMCpack’ successfully unpacked and MD5 sums checked
package ‘optimx’ successfully unpacked and MD5 sums checked
package ‘Rsolnp’ successfully unpacked and MD5 sums checked
package ‘Synth’ successfully unpacked and MD5 sums checked
package ‘truncnorm’ successfully unpacked and MD5 sums checked
package ‘yaml’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\User\AppData\Local\Temp\RtmpGc6ZlF\downloaded_packages
√  checking for file 'C:\Users\User\AppData\Local\Temp\RtmpGc6ZlF\remotes547ca335bd6\insongkim-PanelMatch-7b6b12b/DESCRIPTION' (641ms)
-  preparing 'PanelMatch':
√  checking DESCRIPTION meta-information ... 
-  cleaning src
-  checking for LF line-endings in source and make files
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'PanelMatch_0.0.1.tar.gz'
   
Installing package into ‘C:/Users/User/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package 'PanelMatch' ...
** libs
C:/RBuildTools/3.4/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Users/User/Documents/R/win-library/3.4/RcppArmadillo/include" -I"C:/Users/User/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/User/Documents/R/win-library/3.4/RcppEigen/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Users/User/Documents/R/win-library/3.4/RcppArmadillo/include" -I"C:/Users/User/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/User/Documents/R/win-library/3.4/RcppEigen/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c init.c -o init.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Users/User/Documents/R/win-library/3.4/RcppArmadillo/include" -I"C:/Users/User/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/User/Documents/R/win-library/3.4/RcppEigen/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c matchDID.cpp -o matchDID.o
matchDID.cpp: In function 'Rcpp::List findDDmatched2(int, int, Rcpp::NumericMatrix)':
matchDID.cpp:155:17: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
     if (x1(i,2) == 1 & x1(i-L,1) == x1(i+F,1) & 
                 ^
matchDID.cpp:156:19: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         x1(i-L,0) == x1(i,0)-L & x1(i+F,0) == x1(i,0)+F & 
                   ^
matchDID.cpp:156:44: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         x1(i-L,0) == x1(i,0)-L & x1(i+F,0) == x1(i,0)+F & 
                                            ^
matchDID.cpp:157:20: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         x1(i-1, 2) == 0) {
                    ^
matchDID.cpp:161:21: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         if (x1(j,2) == 0 & x1(j,0) == x1(i,0) & // if the treatment status is zero
                     ^
matchDID.cpp:164:23: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
             x1(j-L,1) == x1(j+F,1) & // for this new unit that just got picked,
                       ^
matchDID.cpp:168:23: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
             x1(j-L,0) == x1(j,0)-L & // make sure that 
                       ^
matchDID.cpp:170:23: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
             x1(j+F,0) == x1(j,0)+F  // same rationale
                       ^
matchDID.cpp: In function 'Rcpp::List findDDNaive(int, int, Rcpp::NumericMatrix)':
matchDID.cpp:207:17: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
     if (x1(i,2) == 1 & x1(i-L,1) == x1(i+F,1) & 
                 ^
matchDID.cpp:208:19: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         x1(i-L,0) == x1(i,0)-L & x1(i+F,0) == x1(i,0)+F & 
                   ^
matchDID.cpp:208:44: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         x1(i-L,0) == x1(i,0)-L & x1(i+F,0) == x1(i,0)+F & 
                                            ^
matchDID.cpp:209:20: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         x1(i-1, 2) == 0) {
                    ^
matchDID.cpp:213:21: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         if (x1(j,2) == 0 & x1(j,0) == x1(i,0) & // if the treatment status is zero
                     ^
matchDID.cpp:216:23: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
             x1(j-L,1) == x1(j+F,1) & // for this new unit that just got picked,
                       ^
matchDID.cpp:220:23: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
             x1(j-L,0) == x1(j,0)-L & // make sure that 
                       ^
matchDID.cpp:222:23: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
             x1(j+F,0) == x1(j,0)+F  // same rationale
                       ^
matchDID.cpp: In function 'Rcpp::List findDDrestricted(int, int, Rcpp::NumericMatrix)':
matchDID.cpp:259:17: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
     if (x1(i,2) == 1 & x1(i-L,1) == x1(i+F,1) & 
                 ^
matchDID.cpp:260:19: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         x1(i-L,0) == x1(i,0)-L & x1(i+F,0) == x1(i,0)+F & 
                   ^
matchDID.cpp:260:44: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         x1(i-L,0) == x1(i,0)-L & x1(i+F,0) == x1(i,0)+F & 
                                            ^
matchDID.cpp:261:20: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         x1(i-1, 2) == 0) {
                    ^
matchDID.cpp:265:21: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
         if (x1(j,2) == 0 & x1(j,0) == x1(i,0) & // if the treatment status is zero
                     ^
matchDID.cpp:268:23: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
             x1(j-L,1) == x1(j+F,1) & // for this new unit that just got picked,
                       ^
matchDID.cpp:272:23: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
             x1(j-L,0) == x1(j,0)-L & // make sure that 
                       ^
matchDID.cpp:274:23: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
             x1(j+F,0) == x1(j,0)+F  // same rationale
                       ^
matchDID.cpp:286:43: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
           if (all_sug(c == d) & sumCpp(e) == 0 & sumCpp(f) == (F+1)){
                                           ^
matchDID.cpp:286:60: warning: suggest parentheses around comparison in operand of '&' [-Wparentheses]
           if (all_sug(c == d) & sumCpp(e) == 0 & sumCpp(f) == (F+1)){
                                                            ^
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Users/User/Documents/R/win-library/3.4/RcppArmadillo/include" -I"C:/Users/User/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/User/Documents/R/win-library/3.4/RcppEigen/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c vector.c -o vector.o
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.1/include" -DNDEBUG  -I"C:/Users/User/Documents/R/win-library/3.4/RcppArmadillo/include" -I"C:/Users/User/Documents/R/win-library/3.4/Rcpp/include" -I"C:/Users/User/Documents/R/win-library/3.4/RcppEigen/include"   -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c wfe.c -o wfe.o
wfe.c: In function 'CalDID':
wfe.c:1507:9: warning: variable 'c_it' set but not used [-Wunused-but-set-variable]
  double c_it;
         ^
wfe.c: In function 'GenWeightsMDID':
wfe.c:2582:14: warning: variable 'y_it' set but not used [-Wunused-but-set-variable]
       double y_it; 
              ^
wfe.c: In function 'GenWeightsFD':
wfe.c:1370:7: warning: 't_it_1' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if ( t_it != t_it_1 ) { /* check whether treatment status changes  */
       ^
wfe.c:1345:6: warning: 't_it' may be used uninitialized in this function [-Wmaybe-uninitialized]
  int t_it;
      ^
wfe.c:1344:6: warning: 'c_it' may be used uninitialized in this function [-Wmaybe-uninitialized]
  int c_it;
      ^
wfe.c: In function 'is_t_t1_same':
wfe.c:1410:6: warning: 't_it_1' may be used uninitialized in this function [-Wmaybe-uninitialized]
   if (t_it == t_it_1) {
      ^
wfe.c:1410:6: warning: 't_it' may be used uninitialized in this function [-Wmaybe-uninitialized]
wfe.c: In function 't_t1_same':
wfe.c:1452:10: warning: 't_ij_1' may be used uninitialized in this function [-Wmaybe-uninitialized]
       if (t_ij == t_ij_1) {
          ^
wfe.c:1452:10: warning: 't_ij' may be used uninitialized in this function [-Wmaybe-uninitialized]
wfe.c: In function 'CalDID':
wfe.c:1718:17: warning: 'diff0' may be used uninitialized in this function [-Wmaybe-uninitialized]
       diffprime += diff0;   
                 ^
wfe.c:1644:17: warning: 'diff0' may be used uninitialized in this function [-Wmaybe-uninitialized]
       diffprime += diff0;   
                 ^
wfe.c:1574:17: warning: 'diff0' may be used uninitialized in this function [-Wmaybe-uninitialized]
       diffprime += diff0;   
                 ^
wfe.c:1543:11: warning: 'y_it1' may be used uninitialized in this function [-Wmaybe-uninitialized]
      diff = y_it - y_it1;
           ^
wfe.c:1543:11: warning: 'y_it' may be used uninitialized in this function [-Wmaybe-uninitialized]
wfe.c:1679:7: warning: 't_it' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (t_it == 1) { /* ifTRUE(sub[,treat]...) == 1 */
       ^
wfe.c: In function 'GenWeightsMDID':
wfe.c:2756:32: warning: 'matchjprime' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (count_treat > 0 && exist[matchjprime][matchiprime-1]==1 && (same[matchjprime][matchiprime-1]==1)) {
                                ^
wfe.c:2756:45: warning: 'matchiprime' may be used uninitialized in this function [-Wmaybe-uninitialized]
    if (count_treat > 0 && exist[matchjprime][matchiprime-1]==1 && (same[matchjprime][matchiprime-1]==1)) {
                                             ^
wfe.c:2742:30: warning: 'minydiff' may be used uninitialized in this function [-Wmaybe-uninitialized]
   } else if (count_treat > 0 && tmpydiff<= minydiff) {
                              ^
wfe.c:2654:36: warning: 'matchjprime' may be used uninitialized in this function [-Wmaybe-uninitialized]
      if (count_control > 0 && exist[matchjprime][matchiprime-1]==1 && (same[matchjprime][matchiprime-1]==1)) {
                                    ^
wfe.c:2654:49: warning: 'matchiprime' may be used uninitialized in this function [-Wmaybe-uninitialized]
      if (count_control > 0 && exist[matchjprime][matchiprime-1]==1 && (same[matchjprime][matchiprime-1]==1)) {
                                                 ^
wfe.c:2640:36: warning: 'minydiff' may be used uninitialized in this function [-Wmaybe-uninitialized]
       } else if (count_control > 0 && tmpydiff<= minydiff) {
                                    ^
wfe.c:2798:16: warning: 'y_it1' may be used uninitialized in this function [-Wmaybe-uninitialized]
     tmpydiff = absolute(y_it1 - y[k]); /* absolute diff */
                ^
C:/RBuildTools/3.4/mingw_64/bin/g++ -shared -s -static-libgcc -o PanelMatch.dll tmp.def RcppExports.o init.o matchDID.o vector.o wfe.o -LC:/PROGRA~1/R/R-34~1.1/bin/x64 -lRlapack -LC:/PROGRA~1/R/R-34~1.1/bin/x64 -lRblas -lgfortran -lm -lquadmath -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.1/bin/x64 -lR
installing to C:/Users/User/Documents/R/win-library/3.4/PanelMatch/libs/x64
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error : object 'merge.formula' is not exported by 'namespace:lasso2'
ERROR: lazy loading failed for package 'PanelMatch'
* removing 'C:/Users/User/Documents/R/win-library/3.4/PanelMatch'
Error: (converted from warning) running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\User\Documents\R\win-library\3.4" "C:/Users/User/AppData/Local/Temp/RtmpGc6ZlF/file547c19c0226/PanelMatch_0.0.1.tar.gz"' had status 1

**Comment by carlokoos** [comment]
Win 10I have neither of the two installed. Best, but I CarloAm 03.12.2018 16:26 schrieb adamrauh <notifications@github.com>:What version of Windows are you using? Do you have RItools or Rcpp installed?

**Comment by adamrauh** [comment]
@carlokoos Could you try installing `Rtools`, as described [here?](http://jtleek.com/modules/01_DataScientistToolbox/02_10_rtools/#1). (Apologies for getting the name wrong the first time. It's Rtools, not RItools.) Then, could you try installing `Rcpp` via install.packages("Rcpp") and see if that installs without error?

**Comment by adamrauh** [comment]
@carlokoos could you re-try installation? I pushed up a patch that should fix it.

**Comment by adamrauh** [comment]
I have good confidence that this should be fixed, so closing until we hear otherwise.
