### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by mlamias** [insongkim/PanelMatch#20]
devtools is fully installed and works fine with other packages, but the following code throws an error after receiving the prompt:   "Building R package from source requires installation of additional build tools.  Do you want to install the additional tools now?"

```
> install_github("insongkim/PanelMatch", dependencies=TRUE)
Downloading GitHub repo insongkim/PanelMatch@master
Error: Could not find tools necessary to compile a package
```

**Comment by adamrauh** [comment]
@mlamias sorry for the delay in getting back to you. We're currently in the process of moving to a new, significantly modified version of the code. Could you try installing the "development" branch version of PanelMatch and see what happens? That would be extremely helpful for our development process. 

Thanks,
Adam

**Comment by adamrauh** [comment]
On second thought, you likely are seeing this error as a result of being on a Windows machine and needing to install `Rtools`. I'm fairly confident that is the issue, so I'm closing this particular ticket, but feel free to open another if the problem continues.
