### ISSUE TITLE
Create a pseudo-panel with PanelMatch

### ISSUE THREAD

**Issue by zmeers** [insongkim/PanelMatch#23]
I am interested in creating a pseudo-panel by matching *across* time periods, not within each time period. Can PanelMatch handle matching across time periods or is the package limited to matching within time period?
Thanks.

**Comment by kosukeimai** [comment]
Can you explain to us exactly what you are trying to do?  Typically, matching with unit across time is a bad idea. See https://imai.fas.harvard.edu/research/FEmatch.html

**Comment by zmeers** [comment]
Sure. I have thought about my problem some more and have discussed with a few colleagues. I am not sure this package really has the capacity to do what we need, but I will expand anyway. 

I have cross sectional individual-level micro data from the US Census. I would like to build a pseudo panel using matching techniques (see http://faculty.wcas.northwestern.edu/~jws780/documents/pseudopanelmatching.pdf) which match units (and refine to one match) over several Census waves, creating a synthetic or pseudo panel. While not as ideal as real panel data, it should be possible to make inferences about individual-level change over time using the pseudo panel. There is a small body of literature on this in the econ literature (see https://openknowledge.worldbank.org/bitstream/handle/10986/15863/PRWP6504.pdf?sequence=5 or https://openknowledge.worldbank.org/bitstream/handle/10986/26471/WPS8033.pdf?sequence=1 for examples of applied work).  

I am not too concerned with finding the right estimator at this point - my co-authors and I would like to construct the pseudo panel first.

**Comment by kosukeimai** [comment]
This sounds more like a record linkage problem.  You might want to check out: https://imai.fas.harvard.edu/research/linkage.html  The software package is available at https://github.com/kosukeimai/fastLink
