### ISSUE TITLE
Match treated units to untreated units in same state

### ISSUE THREAD

**Issue by Mbjoerkh** [insongkim/PanelMatch#26]
Hi. 

My use case requires that treated firms are matched to untreated firms in the same state. What would be the best way to do this? 

Congrats on developing this new method and thank you for creating this package.

**Comment by adamrauh** [comment]
Hi,
Thanks for your interest in the package! Unfortunately there is no easy way to specify this kind of matching currently, but this is likely to be added soon -- hopefully in the next week or so. I think right now the only way to achieve this would be to filter the data set by state and re-run the matching/estimating code each time, which is obviously not super convenient. We'll work on it.

**Comment by adamrauh** [comment]
Hi @Mbjoerkh, I think you should hopefully be able to restrict matches as you described now. There's a new additional argument called "exact.match.variables" in PanelMatch where you can specify columns that you want to match exactly on. Right now, its still under development and only has been tested on time invariant variables...but it would be helpful if you could try it out on the "maha_tweaks" branch.

**Comment by Mbjoerkh** [comment]
Thanks! 

I've installed the "maha_tweaks" branch, and run the below code which returns '"Error in exact.match.variables(pm$statefip) : 
  could not find function "exact.match.variables"'

The code works without the exact.match argument. Is there a special way to load to the "maha_tweaks" branch? 

![image](https://user-images.githubusercontent.com/33209918/57887020-834f7f80-77fc-11e9-98a2-c2a2aeae0896.png)

**Comment by adamrauh** [comment]
Could you try specifying the exact match variables in a character vector? so, something like: ```exact.match.variables = c("statefip")```
