### ISSUE TITLE
Create Test Suite

### ISSUE THREAD

**Issue by adamrauh** [insongkim/PanelMatch#28]
Now that things are pretty stable, it's probably wise that we make unit tests for various important parts of the code to help streamline development. Considering that there have been various informal tests conducted as certain features/bugs were added/removed, I'd propose that we start by taking some of those and turning them into a set of tests with the `testthat` package. An informal/working list of things that should be tested:

- [ ] Make sure that lagged variables are created according to specification
- [ ] Internal indexing system works as intended 
- [ ] Results to simple/toy examples match exactly for PanelMatch, PanelEstimate, get_covariate_balance (obviously this would need to be expanded and made more detailed)
- [ ] specific tests for att, atc, and ate. For instance, qoi = att returns both an "att" and "atc" element in the returned PanelMatch object
- [ ] Tests for each refinement method in PanelMatch
- [ ] use.equal.weights = T/F in get_covariate_balance()
- [ ] Mis-specified problems are caught and handled by error checking code appropriately and helpfully
- [ ] balanced/imbalanced panel data works or doesn't work appropriately
- [ ] forbid.treatment.reversal parameter works when specified as `TRUE`
- [ ] WFE and bootstrap methods correctly produce identical estimates for problems when conditions are met.
- [ ] match.on.missing parameter works
- [ ] all `matched.set` methods work as intended ( `[`, summary, print, etc.)

This is definitely more of a longer term goal. Having your help with this, @erikhw would be extremely helpful.

**Comment by kosukeimai** [comment]
A good idea.  We can use [testthat](https://testthat.r-lib.org/) package for this.
