### ISSUE TITLE
Trouble Loading PanelMatch

### ISSUE THREAD

**Issue by rcb369** [insongkim/PanelMatch#3]
Hi Prof. Kim,

I'm a PhD Candidate in Government at Cornell interested in using your program for matching with TSCS data. I followed your instructions in the readme page, but (after many lines of output) if ends with the error message I pasted below. I would appreciate any help you can offer on this. Warning: I'm pretty novice at R. 

Best,
Rich Barton  

ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [PanelMatch.so] Error 1
ERROR: compilation failed for package ‘PanelMatch’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/PanelMatch’
Installation failed: Command failed (1)

**Comment by insongkim** [comment]
Thanks. Please let us know if installing the development tools available in the following link fixes the problem.  https://cran.r-project.org/bin/macosx/tools/

**Comment by adamrauh** [comment]
Hi @rcb369, try the solution that fits your version of OSX and R from [this](https://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks--lgfortran-and--lquadmath-error/) post.

**Comment by adamrauh** [comment]
Closing this issue, now that some extra documentation has been added
