### ISSUE TITLE
Error in contrasts

### ISSUE THREAD

**Issue by augustocerqua** [insongkim/PanelMatch#34]
Dear authors,

I have been using PanelMatch for since last November and I think it is great. I am now in the process of using it in a new project where I access secured data in an Italian public institution. This means that I cannot directly install the R packages but I can ask them to be installed. The IT guy managed to install PanelMatch and everything seemed fine. However, when I try to run the example code:

_PM.results <- PanelMatch(lag = 4, time.id = "year", unit.id = "wbcode2", 
                         treatment = "dem", refinement.method = "mahalanobis", 
                         data = dem, match.missing = T, 
                         covs.formula = ~ lag("tradewb", 1:4) + lag("y", 1:4), 
                         size.match = 5, qoi = "att",
                         outcome.var = "y", lead = 0:4, forbid.treatment.reversal = FALSE)_

I get the following error:
_Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) :
contrasts can be applied only to factors with 2 or more levels_ 

This is puzzling as the dataset "dem" does not contain any factor variable. I spent a couple of days looking for a solution online but I did not manage to solve this issue.

Of course, I also tried running my own PanelMatch regression but I get the same error message.

Many thanks for your help.

Kind regards,
Augusto Cerqua

**Comment by adamrauh** [comment]
Hi Augusto,

Thanks for using the package! Recently, we updated the package to use a new syntax for lagging variables. If you take a look at the new [README,](https://github.com/insongkim/PanelMatch/blob/master/README.md) you should see an example of the new syntax. Could you try updating your code to align with that and running things again? I suspect that will solve the issue.

Thanks,
Adam

**Comment by augustocerqua** [comment]
Many thanks Adam. That solved my issue.
Regards, 
Augusto

**Comment by adamrauh** [comment]
Great!
