### ISSUE TITLE
errors in PanelMatch regarding the length of vectors

### ISSUE THREAD

**Issue by hijjang13** [insongkim/PanelMatch#35]
Hello Prof. Kim.

I am trying to use PanelMatch for my unbalanced panel, and I got stuck by the following error.

Error in names(new.mset) <- encode.treated.units(treated.ts, treated.ids,  : 
  'names' attribute [48] must be the same length as the vector [38]

It happens when I run PanelEstimate. I tried to change some values in PanelMatch function, but couldn't figure out how to address this issue.

Could you tell me why it happens and how I can address it?

**Comment by adamrauh** [comment]
Could you provide a code sample + some data that will reproduce the error?  It's hard to say much of anything about this error without knowing more about the setup.
