### ISSUE TITLE
Are synthetic controls an estimation option?

### ISSUE THREAD

**Issue by Mbjoerkh** [insongkim/PanelMatch#43]
Hi,

I just have a clarifying question. The package description states 

"..methods include standard matching methods based on propensity score and Mahalanobis distance as well as weighting methods such as synthetic controls." 

I can't seem to see this option anywhere and have updated recently. Just wanted to check if this is available at the moment?

**Comment by insongkim** [comment]
@Mbjoerkh  Thanks for asking this question. The matching methods are used to refine matched sets within `PanelMatch` function using `refinement.method` argument. Specifically, you refine the matched sets (identified based on the treatment history) by using various matching methods using pre-treatment covariates. The default is set to be Mahalanobis distance matching. Please see `refinement.method = "mahalanobis"`.

**Comment by Mbjoerkh** [comment]
Not sure I understand the answer. Just letting you know the description for the package also states it performs "weighting methods such as synthetic controls" (please see line 4). 

![snip](https://user-images.githubusercontent.com/33209918/65647467-cac8f200-dfcc-11e9-9f34-f44d11ef9731.PNG)

**Comment by insongkim** [comment]
Oh, I see. Researchers may use the weights from synthetic control methods to refine matched sets. Unfortunately, the current version of the package does not support an automatic implementation of this. We will update the description accordingly. 

Alternatively, you can include past outcomes in `covs.formula` (e.g., `I(lag(y, 1:4))`) to adjust for pre-treatment outcome values. I hope this makes sense. Thank you very much.

**Comment by Mbjoerkh** [comment]
Ah, I understand. Thank you for clarifying.
