### ISSUE TITLE
How do results compare with other methods / Are my results significant?

### ISSUE THREAD

**Issue by Mbjoerkh** [insongkim/PanelMatch#45]
Hi again, 

I've come across this issue a couple times where I appear to have found a significant result but where for the sake of simplicity, one data point is not significant. In the screenshot below, my eyeballing suggests there's a positive effect, on average, but obviously t+0 is not significant. 

Is there a way to calculate the average effect (and corresponding standard errors) as opposed to the average effect at t0, t1, t2, and so on?

More generally, I think it would be very helpful if it is made easier to compare the results found with PanelMatch/PanelEstimate, with those of other more traditional methods such as 2WFE etc. 

![signi](https://user-images.githubusercontent.com/33209918/66433025-64d96300-e9ed-11e9-8431-ec8f3718592f.PNG)

**Comment by kosukeimai** [comment]
Thanks for the suggestion.  It's a little tricky because they are all correlated, but we will add this to the to-do list.

**Comment by Mbjoerkh** [comment]
Thanks. 

It would seem to me that one might be able to use other existing estimation methods/packages on the matched sets from PanelMatch, but maybe I underestimate the standard error calculations. In any case, I would think this will be a common crossroad for users as reviewers will want to know.

Thanks again!

**Comment by adamrauh** [comment]
Closing this issue as I believe it has been implemented -- discussed over in #99
