### ISSUE TITLE
R session aborting

### ISSUE THREAD

**Issue by elsavoytas** [insongkim/PanelMatch#46]
Hello,

I have a very large dataset (91 million observations), and when I run PanelMatch, my R session aborts. I have had some success running the script on my university's cluster computers, but I was wondering if you had tips I might implement to run the code locally.

Thanks,
Elsa

**Comment by kosukeimai** [comment]
Hey Elsa, I suggest that you subset the data based on key variables.  For example, if gender is known to be important, you can analyze men and women separately.  This way, you can reduce the size of data for matching.

**Comment by elsavoytas** [comment]
Thanks Kosuke. Appreciate the tip!
