### ISSUE TITLE
Issues with Installation of PanelMatch, Non-Zero Exit Status 

### ISSUE THREAD

**Issue by smcqueen221** [insongkim/PanelMatch#48]
I have tried downloading PanelMatch via instructions listed have failed. I keep getting an error message for  "non-zero exit status error".  I also tested this in R (without Rstudio) and got the same result. I am using the newest version of R (3.6.2) and I use Mac OS El Capitan version 10.11.6. 

<img width="1024" alt="Screen Shot 2020-01-01 at 5 49 08 PM" src="https://user-images.githubusercontent.com/59483635/71738732-81870a80-2e25-11ea-82ef-d32e8019565e.png">

I've also attached my session information, if that is helpful. Any advice is greatly appreciated! Happy to submit additional  information needed. 

<img width="579" alt="Screen Shot 2020-01-01 at 5 49 32 PM" src="https://user-images.githubusercontent.com/59483635/71738812-c317b580-2e25-11ea-947f-026a30fcf96f.png">
<img width="799" alt="Screen Shot 2020-01-01 at 5 49 20 PM" src="https://user-images.githubusercontent.com/59483635/71738814-c4e17900-2e25-11ea-9bcc-1002937670f8.png">
<img width="579" alt="Screen Shot 2020-01-01 at 5 49 32 PM" src="https://user-images.githubusercontent.com/59483635/71738817-c6ab3c80-2e25-11ea-83d0-490710d62ffb.png">
<img width="659" alt="Screen Shot 2020-01-01 at 5 49 47 PM" src="https://user-images.githubusercontent.com/59483635/71738819-c7dc6980-2e25-11ea-95c2-e1f82e656f9e.png">

**Comment by adamrauh** [comment]
hey @smcqueen221 , thanks for using the package! Could you try installing the latest version of gfortran for El Capitan from [here](https://github.com/fxcoudert/gfortran-for-macOS/releases), then restarting R and attempting to install the package again?

**Comment by smcqueen221** [comment]
Thanks for responding and sorry for the delay. After hitting a few errors uninstalling the original gfortran- it worked and downloaded! Thank you - thank you!

**Comment by adamrauh** [comment]
Glad that worked!
