### ISSUE TITLE
Finding ATT with T=1 as the treatment.  Set ATT=2 to find ATT with T=0 as the treatment

### ISSUE THREAD

**Issue by marcgrinberg** [insongkim/PanelMatch#49]
When you run PanelMatch with refinement.method="CBPS.weight" you get this message: "Finding ATT with T=1 as the treatment.  Set ATT=2 to find ATT with T=0 as the treatment"

My guess is that this is a product of a call to the CBPS package, which prints this message. But is there any way to do this from within the PanelMatch function?

**Comment by adamrauh** [comment]
@marcgrinberg Indeed this is something that is a result of the CBPS package. I'm not quite sure what you're trying to do within PanelMatch, but it sounds like swapping `atc` in for `att` might help?
