### ISSUE TITLE
Error in data.frame

### ISSUE THREAD

**Issue by EHM20** [insongkim/PanelMatch#52]
Does anyone know what this error message means/have suggestions for fixing it? Thanks!

Error in `[[<-.data.frame`(`*tmp*`, i, value = c(NA, 1L, 1L, 1L, 1L, 1L, : replacement has 60 rows, data has 15

<img width="803" alt="Screen Shot 2020-03-31 at 3 38 02 PM" src="https://user-images.githubusercontent.com/62962105/78068019-b7c12100-7365-11ea-8543-e02acaf21579.png">

**Comment by adamrauh** [comment]
hi @EHM20, thanks for trying out the package! I don't see anything immediately wrong with the way you've specified things here. It's hard to say much more without seeing the structure of your data. Could you try to generate a smaller reproducible example?

**Comment by EHM20** [comment]
Hi @adamrauh , thanks for your response! I fixed the issue-- it had to do with the definition of variables.

**Comment by adamrauh** [comment]
glad you were able to solve the issue!
