### ISSUE TITLE
Lead in PanelMatch

### ISSUE THREAD

**Issue by pzy0337** [insongkim/PanelMatch#54]
The current version returned an error message when I specified `lead` as a vector (e.g., 0:2). The message also told me to run the function for each increment of `lead`. Will this issue be fixed in the future?

**Comment by adamrauh** [comment]
I could be wrong, but this sounds like an old error. Could you try updating?

**Comment by sergimartinezeui** [comment]
Hi,

When including negative values to the specification of 'lead' part of the PanelMatch command (e.g., lead = -2:1), I get results including pre-treatment placebos (t-2, in that case) compared to the baseline year (t-1).  I guess that could be useful for assessing how well matching works for balancing samples and evaluating the pre-treatment parallel trend. I'm not sure, however, to what extent can this be appropriate given that the t-2 estimate is compared to t-1, if I understood it correctly. Is there a way to vary the baseline year?

Thanks!
 
![plotmatchlagsestimates](https://user-images.githubusercontent.com/59883775/82318045-7943fc00-99cf-11ea-98ad-f9f302ab8ba5.png)

**Comment by adamrauh** [comment]
@sergimartinezeui After looking a little bit into this, the package currently does not support this kind of functionality -- so I pushed a patch that will throw an error if the user provides a negative value in the lead argument as a temporary measure. 

That said, we think this would be a useful feature and will work on adding this in relatively soon, most likely. I created a fresh ticket to track progress [here](https://github.com/insongkim/PanelMatch/issues/59)
