### ISSUE TITLE
get_covariate_balance: before matching?

### ISSUE THREAD

**Issue by thaleswest** [insongkim/PanelMatch#67]
Is there a way to check the covariate balance before matching? It would be interesting if we could readily check/plot those data (as you do in your Figure 5 from Imai et al. 2018 "Matching Methods for Causal Inference with Time-Series Cross-Sectional Data").

**Comment by adamrauh** [comment]
Hi @thaleswest , thanks for using the package! If I understand correctly, I believe there are two ways to accomplish this. You do need to create matched sets, so you are still "matching" in that sense, but you can compare the pre and post refinement covariate balance in two ways. 

1) you could run PanelMatch with `refinement.method = none`, and then use the `get_covariate_balance` function
2) you run PanelMatch with any kind of refinement you like, but when you use `get_covariate_balance`, you can set `use.equal.weights = TRUE`

There are some examples of this in the [vignette](https://github.com/insongkim/PanelMatch/blob/master/vignettes/using_panelmatch.Rmd), and some additional information about the arguments in the function documentation. 

Hopefully that helps, but let me know if you have other questions.
