### ISSUE TITLE
the matched control units may include those units who receive the treatment after time t but before the outcome is measured at time t + F. 

### ISSUE THREAD

**Issue by augustocerqua** [insongkim/PanelMatch#71]
Dear Authors,

Many thanks for continuing working on additional features of PanelMacth. In one of the papers in which I use PanelMatch, I'd like to run a sensitivity check in which,  using the words at page 17 of your article (Sept 2020 version), "the matched control units do not include those units who receive the treatment after time t but before the outcome is measured at time t + F". Is this possible in PanelMatch at this stage? If so, how?

Many thanks,
Augusto Cerqua

**Comment by asmae-toumi** [comment]
I'm wondering about the same thing. Augusto, would you mind sharing your finding? Thank you!

**Comment by augustocerqua** [comment]
Dear Asmae-Toumi, it should be enough to add "forbid.treatment.reversal = TRUE" in the PanelMatch command
