### ISSUE TITLE
error when using msm

### ISSUE THREAD

**Issue by asmae-toumi** [insongkim/PanelMatch#72]
Hi, 

I encountered the following error when setting the refinement method to "CBPS.msm.weight" and specifying a lead time:

"Error in enforce_lead_restrictions(msets, ordered.data, max(lead), time.id,  : 
  estimation not possible: All treated units are missing data necessary for the calculations to proceed"

But it works when I don't specify a lead time. I'm having trouble understanding why. Thanks!

**Comment by adamrauh** [comment]
Hi @asmae-toumi, thanks for using the package. This is definitely odd. Would you mind sharing a reproducible example? If you don't want to post your data, feel free to email me.

**Comment by adamrauh** [comment]
resolved via email: the issue was related to the amount of variation in the data set and the restrictions placed on the lead window in the MSM methods.
