### ISSUE TITLE
Is it possible to identify the units selected when refinining the matched sets?

### ISSUE THREAD

**Issue by augustocerqua** [insongkim/PanelMatch#73]
Dear Authors,

Many thanks for continuing to update this very useful command. I have a question about the identification of the control units selected by the matching estimator.
Let's say I am using Mahalanobis matching with 3 neighbors. Is it possible to know which are the 3 neighbors matched with each treated unit?
I think this might be useful for 2 reasons:
i) to have an idea of the geographical distribution of weights (in case one is using area-level data);
ii) to plot individual treatment effects versus a covariate to investigate the possible relationship (not necessarily causal) between ATT and a relevant variable (suggested by theoretical arguments).

Many thanks,
Augusto Cerqua

**Comment by insongkim** [comment]
@augustocerqua Thanks for using the package. The matched set object should contain the information that you are looking for. I hope that the wiki page that we created can be a useful point to start: https://github.com/insongkim/PanelMatch/wiki/Matched-Set-Objects

Thanks.

**Comment by augustocerqua** [comment]
Many thanks In Song. I've managed to get the individual treatment effects
