### ISSUE TITLE
moderating variable function

### ISSUE THREAD

**Issue by hijjang13** [insongkim/PanelMatch#74]
Hi,

I recently had my R reinstalled, and reinstalled the PanelMatch package. It seems the moderating variable function does not work. I installed this package from github, using devtools.

Is there any issue with this function?

**Comment by adamrauh** [comment]
Hi @hijjang13,

Could you provide a bit more information or a reproducible example? What error are you getting? We did update the moderating variable code to change the argument names at one point.

**Comment by hijjang13** [comment]
Hi @adamrauh 

I ran the following code.

PE.results <- PanelEstimate(sets = PM.results, data = Cleaned_matching, moderating.variable = 'failed')

And I got the following error.

unused argument (moderating.variable = "demo")

I may have run a depricated code?

**Comment by hijjang13** [comment]
The error was :unused argument (moderating.variable = "failed")*

**Comment by adamrauh** [comment]
ah, yeah. Try changing `moderating.variable` to `moderator`
