### ISSUE TITLE
error：“please convert time id to consecutive integers”？

### ISSUE THREAD

**Issue by Amy1028** [insongkim/PanelMatch#76]
Hi，I have a question. I am sure I have converted “year” variable to integer,with increasing by 1 each time. But it always reports  “please convert time id to consecutive integers” and I can‘t continue my analysis，panalmatch or panelestim. I don’t know if anybody meet problem like this.Can someone help me to solve it?
Thank you very much!

**Comment by Amy1028** [comment]
I have converted all variables into integer，but it still reports there are some non-numerical data in “time treatment or id”.
how can I solve it?

**Comment by dkwu02** [comment]
Hello, I also see the report “please convert time id to consecutive integers”, but I'm very sure the time variable is consecutive. How can I solve it?
Thanks!

**Comment by adamrauh** [comment]
@Amy1028 @dkwu02 Could you post a sample of your code?

**Comment by dkwu02** [comment]
@adamrauh  Hello! I have a data frame called "fr". My unit variable is "cnum". Each integer (1,2,3,...,192) denotes a country. My time variable is "year". Each value (1985, 1986,..., 2015) denotes one year. I'm very sure it is a consecutive variable, and the whole dataset is strongly balanced (number of observations = 192*31). 
I type the following code to see the treatment variation plot:
`DisplayTreatment(unit. id = "cnum", time. id = "year", legend.position = "none", xlab="year", ylab="Country", treatment = "law", data=fr)`
And it reports "please convert time id to consecutive integers".

**Comment by Amy1028** [comment]
> Hello! I got the point! The time variable is required to set integer type.
> Thanks!

Thanks you！

**Comment by liulin76** [comment]
Which command do you use?
