### ISSUE TITLE
Treatment reversal

### ISSUE THREAD

**Issue by guilhermekirch** [insongkim/PanelMatch#77]
Hi, I have a question about your very useful package. When I want to study a treatment reversal (like the authoritarian reversal in the paper) I need to redefine the treatment variable or is there a parameter in the PanelMatch function that control this behavior? Thank you in advance!

**Comment by adamrauh** [comment]
Hi there, thanks for using the package. It sounds like you might be interested in setting `qoi = atc`.

**Comment by guilhermekirch** [comment]
Hi Adam, thank for your reply. I think I was not clear in my question. I will use the dem event to ilustrate my point. The atc (with dem as treatment variable) is the effect that democratization would cause on a country that remains authoritarian (dem_(i, t) =0, dem(i, t-1) = 0, relative to another country with dem(j, t) = 1, dem(j, t-1) = 0). The treatment reversal is the att of a country that reverses from democracy to authoritarian (dem(i, t) = 0, dem(i, t-1) = 1, relative to another country with dem(j, t) = 1, dem(j, t-1) = 1). If I am right, it is necessary to redefine the treatment variable to do this analysis. It would be nice if your package as a function to automate this process.

**Comment by adamrauh** [comment]
A year late, but I believe this has now been solved in subsequent versions of the package. If I understand correctly, @guilhermekirch is describing what is now implemented as the "art". We previously had this incorrectly labeled as the atc. Now, the att, atc, art, and ate are all correctly implemented (hopefully).
