### ISSUE TITLE
Possible to recover treatment effect for each unit separately?

### ISSUE THREAD

**Issue by amtambe** [insongkim/PanelMatch#79]
Is it possible to recover the treatment effect for each treated unit? I can see the matched sets for each treated unit but am not sure how to see the treatment effect divided by unit. 
If there isn't an existing command, is there straightforward way for me to edit the code myself to achieve this? 
Thanks in advance for your help!

**Comment by adamrauh** [comment]
Hi @amtambe , sorry for the delay in getting back to you. Thank you for raising this. Currently, this is not a built in feature of the package, but we are working on it. In the meantime, it might be helpful to check out our vignette for `matched.set` objects: https://github.com/insongkim/PanelMatch/blob/master/vignettes/matched_set_objects.Rmd 

Hopefully that helps -- you should be able to extract control unit weights fairly easily and then use that to calculate things manually.

**Comment by adamrauh** [comment]
This feature is now implemented in the `getSetTreatmentEffects()` function.
