### ISSUE TITLE
PanelEstimate() Returns 0s when qoi = "atc"

### ISSUE THREAD

**Issue by DamianBoldt** [insongkim/PanelMatch#81]
Hello, 
I have been utlizing the PanelMatch package in a project and I recently attempted to estimate the ATC and it returned zeros for every estimate as well as zeros for every confidence interval. It has not returned an error or warning message and the PanelMatch object that I am passing to PanelEstimate() contains a decent amount of control units in the matched sets. I am unsure why it will not return an estimate for the ATC because it was able to successfully estimate the ATT and there is a decent amount of variation in treatment assignment. The only potential explanation I could think of is that there are not a lot of observations that experience the outcome variable. However, it does successfully estimate the ATT. 
This is what the plot looks like:

![image](https://user-images.githubusercontent.com/54724797/119615972-acc91b80-bdc5-11eb-8a2e-486f9e2e2c46.png)

Any help that you could provide in explaining why estimating the ATC would return all zeros would be greatly appreciated. 

Sincerely, 
Damian Boldt

**Comment by adamrauh** [comment]
Hi @DamianBoldt thanks for finding this. This is certainly odd. Would you mind sharing some code/data/a reproducible example for me? If you don't want to post anything publicly, you can email me as well. It's hard to say much otherwise, but I'm happy to look into this.

**Comment by adamrauh** [comment]
Resolved via email -- this was just an artifact of the data.
