### ISSUE TITLE
dem data missing covariates used in example

### ISSUE THREAD

**Issue by jbisbee1** [insongkim/PanelMatch#9]
The example code provided doesn't work with the dem data that is loaded in the current version of the package due to missing columns. As shown below, the data provided only includes the `tradewb` variable.

`> require(PanelMatch)
> data(dem)
> dem %>% head()
  wbcode2 year dem  y  tradewb
1       2 1960   0 NA       NA
2       2 1961   0 NA 11.47824
3       2 1962   0 NA 12.97522
4       2 1963   0 NA 18.52119
5       2 1964   0 NA 25.75280
6       2 1965   0 NA 29.31384`

**Comment by adamrauh** [comment]
Hi James, thanks for pointing this out. The documentation over on the [development branch](https://github.com/insongkim/PanelMatch/tree/development) should have a working example, if that's helpful.

**Comment by adamrauh** [comment]
Should be fixed in the main branch now
