### ISSUE TITLE
Bootstrap Confidence Intervals

### ISSUE THREAD

**Issue by RobbyMax1999** [insongkim/PanelMatch#91]
Hello and thanks for this great package and contribution to the community. I have a question about the bootstrap confidence intervals. Some of the confidence intervals I am getting turn out to be asymmetrically bounded at zero into one direction for the att estimates (one example: the att estimate is very small, and the confidence interval skewed heavily away from zero into one direction and zero on the other). Would you have any insight if and/or under which conditions such a result makes sense? Thanks, R.

**Comment by kosukeimai** [comment]
This can happen especially in a small sample.
